const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:JSON_HEADERS});
const ok=data=>json({ok:true,data});
const fail=(error,status=400,code="REQUEST_FAILED",details=null)=>json({ok:false,error:String(error||"Grading Copilot request failed."),code,...(details?{details}:{})},status);
class CanvasRequestError extends Error{constructor(message,{status=502,code="CANVAS_REQUEST_FAILED",endpoint="",canvasMessage=""}={}){super(message);this.name="CanvasRequestError";this.status=status;this.code=code;this.endpoint=endpoint;this.canvasMessage=canvasMessage;}}
function config(env){const base=new URL(String(env.CANVAS_BASE_URL||"https://nku.instructure.com"));if(base.protocol!=="https:"||base.hostname!=="nku.instructure.com")throw new Error("Canvas host is not approved.");const token=String(env.CANVAS_ACCESS_TOKEN||"").trim();if(!token)throw new Error("Canvas credentials are not configured.");return{base:base.origin,token};}
const headers=(token,extra={})=>({Authorization:`Bearer ${token}`,Accept:"application/json",...extra});
const enc=v=>encodeURIComponent(String(v));
async function requestJson(url,init={}){const response=await fetch(url,init);const text=await response.text();let body={};try{body=text?JSON.parse(text):{};}catch{body={raw:text};}if(!response.ok){const endpoint=new URL(url).pathname;const remote=String(body?.errors?.[0]?.message||body?.message||body?.error||"").trim();if(response.status===401)throw new CanvasRequestError("Canvas rejected the configured access token.",{status:401,code:"CANVAS_TOKEN_REJECTED",endpoint,canvasMessage:remote});if(response.status===403)throw new CanvasRequestError("Canvas denied this request.",{status:403,code:"CANVAS_ACCESS_DENIED",endpoint,canvasMessage:remote});if(response.status===404)throw new CanvasRequestError("Canvas could not find the requested resource.",{status:404,code:"CANVAS_RESOURCE_NOT_FOUND",endpoint,canvasMessage:remote});throw new CanvasRequestError(remote||`Canvas request failed (${response.status}).`,{status:response.status,endpoint,canvasMessage:remote});}return{body,response};}
async function paged(url,token){const all=[];let next=url;for(let page=0;next&&page<30;page++){const {body,response}=await requestJson(next,{headers:headers(token)});if(!Array.isArray(body))throw new Error("Canvas returned an unexpected list response.");all.push(...body);const link=response.headers.get("link")||"";const m=link.match(/<([^>]+)>;\s*rel="next"/);next=m?m[1]:"";}return all;}
async function api(request,env){const c=config(env),url=new URL(request.url),parts=url.pathname.split("/").filter(Boolean);
 if(request.method==="GET"&&url.pathname==="/api/status")return ok({service:"Grading Copilot",canvasConfigured:true,canvasHost:new URL(c.base).hostname,writesEnabled:env.CANVAS_WRITE_ENABLED==="true"});
 if(request.method==="GET"&&url.pathname==="/api/courses")return ok(await paged(`${c.base}/api/v1/courses?enrollment_type=teacher&enrollment_state=active&per_page=100`,c.token));
 if(request.method==="GET"&&parts[0]==="api"&&parts[1]==="courses"&&parts[3]==="assignments"&&parts.length===4)return ok(await paged(`${c.base}/api/v1/courses/${enc(parts[2])}/assignments?per_page=100&order_by=due_at`,c.token));
 if(request.method==="GET"&&parts[0]==="api"&&parts[1]==="courses"&&parts[3]==="assignments"&&parts[5]==="submissions")return ok(await paged(`${c.base}/api/v1/courses/${enc(parts[2])}/assignments/${enc(parts[4])}/submissions?include[]=user&per_page=100`,c.token));
 if(request.method==="POST"&&url.pathname==="/api/post-grade"){if(env.CANVAS_WRITE_ENABLED!=="true")return fail("Canvas writes are disabled.",403,"WRITES_DISABLED");const p=await request.json();if(p.confirmWrite!==true)return fail("Explicit confirmWrite=true is required.",400,"CONFIRMATION_REQUIRED");const body=new URLSearchParams();body.set("submission[posted_grade]",String(p.grade));body.set("comment[text_comment]",String(p.feedback||""));await requestJson(`${c.base}/api/v1/courses/${enc(p.courseId)}/assignments/${enc(p.assignmentId)}/submissions/${enc(p.userId)}`,{method:"PUT",headers:headers(c.token,{"content-type":"application/x-www-form-urlencoded;charset=UTF-8"}),body:body.toString()});const {body:verified}=await requestJson(`${c.base}/api/v1/courses/${enc(p.courseId)}/assignments/${enc(p.assignmentId)}/submissions/${enc(p.userId)}?include[]=submission_comments`,{headers:headers(c.token)});return ok({verified:true,verification:"fresh Canvas read after write",submission:verified});}
 return fail("Not found",404,"NOT_FOUND");
}
export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname.startsWith("/api/")){try{return await api(request,env);}catch(error){if(error instanceof CanvasRequestError)return fail(error.message,error.status,error.code,{endpoint:error.endpoint,canvasMessage:error.canvasMessage||null});return fail(error?.message||error,500,"GRADING_COPILOT_ERROR");}}return env.ASSETS.fetch(request);}};
